name = "imgprocess"
main = "src/index.ts"
assets = { directory = "./public" }
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "example.com", custom_domain = true }
]

[observability]
enabled = true

[[r2_buckets]]
binding = "IMAGE_BUCKET"             # This is how you'll access it in your Worker code
bucket_name = "imagebucket" 
preview_bucket_name = "imagebucket"

[vars]
R2_DOMAIN = "r2.example.com"
TOKEN = " openssl rand -base64 32"